---
title: "<c**... in R**"
author: "Wyclife Agumba Oluoch (wyclifeoluoch@gmail.com)"
date: "<center>`r Sys.time()`</center>"
bibliography: 
  - bib/packages.bib
nocite: '@*'
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: darkly
    #highlight: pygments
#bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
packages <- c("base",
              'knitr',
              'rmarkdown',
              'prettydoc')
installed_packages <- packages %in% rownames(installed.packages())
if(any(installed_packages == FALSE)){
  install.packages(packages[!installed_packages])
}
lapply(packages, library, character.only = TRUE) |> invisible()
```

```{r write_bib, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::write_bib(c(
  .packages(), packages
), 'bib/packages.bib')
```

# Background

Here we highlight a bit of information about the topic under discussion. And it is also super simple to add citation [@stave2006]!

## \|- This is a sub-heading drawing from above heading

Another bit of information that should fall under some bit of sub-heading.

All the cited literature sources should then be under References below: \# References
